name: Build & Release Panel

on:
  push:
    branches: [ "main" ]
    tags:     [ "[0-9]+.[0-9]+.[0-9]+" ]

permissions:
  contents: write  # required to create releases & upload assets

concurrency:
  group: panel-release-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: "24.x"
  OUTPUT_DIR: "build"

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: gui/package-lock.json

      - name: Install deps
        working-directory: gui
        run: npm ci

      - name: Build
        working-directory: gui
        run: npm run build

      - name: Ensure build output exists
        run: |
          if [ ! -d "gui/${OUTPUT_DIR}" ]; then
            echo "Expected build output at gui/${OUTPUT_DIR} not found."
            exit 1
          fi

      - name: Create tarball
        run: |
          mkdir -p dist
          if [[ "${{ startsWith(github.ref, 'refs/tags/') }}" == "true" ]]; then
            FILE_NAME="panel-${{ github.ref_name }}.tar.gz"   # e.g. panel-v1.2.3.tar.gz
          else
            FILE_NAME="panel-nightly.tar.gz"
          fi
          echo "FILE_NAME=$FILE_NAME" >> $GITHUB_ENV
          tar -C "gui/${OUTPUT_DIR}" -czf "dist/${FILE_NAME}" .

      # Nightly prerelease (overwrite asset on every main push)
      - name: Upload to nightly prerelease
        if: github.ref == 'refs/heads/main'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/${{ env.FILE_NAME }}
          asset_name: panel-nightly.tar.gz
          tag: nightly
          release_name: Nightly
          body: "Automated nightly panel build from main."
          prerelease: true
          overwrite: true

      # Versioned release for tags like v1.2.3
      - name: Upload to versioned release
        if: startsWith(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/${{ env.FILE_NAME }}
          asset_name: ${{ env.FILE_NAME }}
          tag: ${{ github.ref_name }}        # uses the pushed tag (e.g. v1.2.3)
          release_name: ${{ github.ref_name }}
          body: "SvelteKit panel build for ${{ github.ref_name }}."
          prerelease: false
          overwrite: false
